Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -41,3 +41,20 @@ jobs:
 
     - name: Test
       run: go test -v ./...
+      
+            
+    - name: Coverage test
+      env:
+          TARGET_COVERAGE: 70
+      run: |
+            echo "Coverage threshold test ..."
+            echo "Threshold             : $TARGET_COVERAGE %"
+            go test ./... -coverprofile coverage.out -covermode count
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TARGET_COVERAGE" | awk '{print ($1 > $2)}') )); then
+                echo "Success"
+            else
+                echo "Failed"
+                exit 1
+            fi
